#!/bin/sh
export LD_PRELOAD=libstdc++.so.6
export PYTHONPATH=$PYTHONPATH:/Users/yangzhl/p4vasp/python-packages
#export APPMENU_DISPLAY_BOTH=1
export UBUNTU_MENUPROXY=0
export P4VASP_HOME=/Users/yangzhl/p4vasp
exec python /Users/yangzhl/p4vasp/bin/p4v.py "$@"
